struct vIn {
  float4 pos : POSITION;
  float weight : BLENDWEIGHT;
  float3 norm : NORMAL;
  float4 diffuse : DIFFUSE;
  float4 specular : SPECULAR;
//  float point_size : PSIZE;
//  float4 back_diffuse : BACK_DIFFUSE;
//  float4 back_specular : BACK_SPECULAR;
  float4 tex0 : TEXCOORD0;
  float4 tex1 : TEXCOORD1;
  float4 tex2 : TEXCOORD2;
  float4 tex3 : TEXCOORD3;
};

struct vOut {
  float4 pos : POSITION;
  float4 col : COLOR0;
};

#define ATTR_WEIGHT 0
#define ATTR_NORMAL 1
#define ATTR_DIFFUSE 2
#define ATTR_SPECULAR 3
#define ATTR_FOG_COORD 4
#define ATTR_POINT_SIZE 5
#define ATTR_BACK_DIFFUSE 6
#define ATTR_BACK_SPECULAR 7
#define ATTR_TEX0 8
#define ATTR_TEX1 9
#define ATTR_TEX2 10
#define ATTR_TEX3 11

vOut main(vIn I, uniform int test_attribute, uniform float4 mask, uniform float2 bias_and_multiplier) {
  vOut result;

  result.pos = I.pos;

  float4 default_value = float4(0.0, 0.0, 0.0, 1.0);
  float4 calculated = float4(1.0, 0.0, 0.0, 0.75);

  // Keep in sync with attribute_carryover_test.h
  if (test_attribute == ATTR_WEIGHT) {
    calculated = float4(I.weight, 1.0, 1.0, 1.0);
  } else if (test_attribute == ATTR_NORMAL) {
    calculated = float4(I.norm, 1.0);
  } else if (test_attribute == ATTR_DIFFUSE) {
    calculated = I.diffuse;
  } else if (test_attribute == ATTR_SPECULAR) {
    calculated = I.specular;
  } else if (test_attribute == ATTR_TEX0) {
    calculated = I.tex0;
  } else if (test_attribute == ATTR_TEX1) {
    calculated = I.tex1;
  } else if (test_attribute == ATTR_TEX2) {
    calculated = I.tex2;
  } else if (test_attribute == ATTR_TEX3) {
    calculated = I.tex3;
  }

  // Allow inputs with ranges outside of 0..1 to be scaled into color range.
  calculated += bias_and_multiplier.x;
  calculated *= bias_and_multiplier.y;

  result.col = mix(default_value, clamp(calculated, 0.0, 1.0), mask);

  return result;
}
