#ifndef NXDK_PGRAPH_TESTS_TESTS_HOST_STUBS_NV2ASTATE_H_
#define NXDK_PGRAPH_TESTS_TESTS_HOST_STUBS_NV2ASTATE_H_

typedef int SDL_PixelFormatEnum;

namespace PBKitPlusPlus {

class NV2AState {
 public:
  NV2AState() = default;
  virtual ~NV2AState() = default;

  [[nodiscard]] float GetFramebufferWidthF() const { return 640.f; }
  [[nodiscard]] float GetFramebufferHeightF() const { return 480.f; }

  enum DrawPrimitive {
    PRIMITIVE_POINTS = NV097_SET_BEGIN_END_OP_POINTS,
    PRIMITIVE_LINES = NV097_SET_BEGIN_END_OP_LINES,
    PRIMITIVE_LINE_LOOP = NV097_SET_BEGIN_END_OP_LINE_LOOP,
    PRIMITIVE_LINE_STRIP = NV097_SET_BEGIN_END_OP_LINE_STRIP,
    PRIMITIVE_TRIANGLES = NV097_SET_BEGIN_END_OP_TRIANGLES,
    PRIMITIVE_TRIANGLE_STRIP = NV097_SET_BEGIN_END_OP_TRIANGLE_STRIP,
    PRIMITIVE_TRIANGLE_FAN = NV097_SET_BEGIN_END_OP_TRIANGLE_FAN,
    PRIMITIVE_QUADS = NV097_SET_BEGIN_END_OP_QUADS,
    PRIMITIVE_QUAD_STRIP = NV097_SET_BEGIN_END_OP_QUAD_STRIP,
    PRIMITIVE_POLYGON = NV097_SET_BEGIN_END_OP_POLYGON,
  };
};

}  // namespace PBKitPlusPlus

#endif  // NXDK_PGRAPH_TESTS_TESTS_HOST_STUBS_NV2ASTATE_H_
