#ifndef SDL_H
#define SDL_H

enum SDL_PixelFormatEnum {
  SDL_PIXELFORMAT_ARGB8888,
  SDL_PIXELFORMAT_ABGR8888,
  SDL_PIXELFORMAT_RGBA8888,
  SDL_PIXELFORMAT_BGRA8888,
  SDL_PIXELFORMAT_RGB565,
  SDL_PIXELFORMAT_ARGB1555,
  SDL_PIXELFORMAT_ARGB4444,
  SDL_PIXELFORMAT_INDEX8,
};

typedef void *SDL_Surface;

#endif  // SDL_H
