// Generated by collada_converter.py

#include "flat_grid_model.h"

#include "flat_grid_mesh.h"

uint32_t FlatGridModel::GetVertexCount() const { return kNumVertices; }
const float* FlatGridModel::GetVertexPositions() const { return kPosition; }
const float* FlatGridModel::GetVertexNormals() const { return kNormal; }
