// Generated by collada_converter.py
#ifndef _FLAT_GRID_MODEL_H_
#define _FLAT_GRID_MODEL_H_

#include "model_builder.h"

class FlatGridModel : public SolidColorModelBuilder {
 public:
  FlatGridModel() : SolidColorModelBuilder() {}
  FlatGridModel(const vector_t &diffuse, const vector_t &specular) : SolidColorModelBuilder(diffuse, specular) {}

  [[nodiscard]] uint32_t GetVertexCount() const override;

 protected:
  [[nodiscard]] const float *GetVertexPositions() const override;
  [[nodiscard]] const float *GetVertexNormals() const override;
};

#endif  // _FLAT_GRID_MODEL_H_
