// Generated by collada_converter.py

#include "light_control_test_mesh_torus_model.h"

#include "light_control_test_mesh_torus_mesh.h"

uint32_t LightControlTestMeshTorusModel::GetVertexCount() const { return kNumVertices; }
const float* LightControlTestMeshTorusModel::GetVertexPositions() const { return kPosition; }
const float* LightControlTestMeshTorusModel::GetVertexNormals() const { return kNormal; }
