// Generated by collada_converter.py

#include "light_control_test_mesh_suzanne_model.h"

#include "light_control_test_mesh_suzanne_mesh.h"

uint32_t LightControlTestMeshSuzanneModel::GetVertexCount() const { return kNumVertices; }
const float* LightControlTestMeshSuzanneModel::GetVertexPositions() const { return kPosition; }
const float* LightControlTestMeshSuzanneModel::GetVertexNormals() const { return kNormal; }
