// Generated by collada_converter.py

#include "light_control_test_mesh_sphere_model.h"

#include "light_control_test_mesh_sphere_mesh.h"

uint32_t LightControlTestMeshSphereModel::GetVertexCount() const { return kNumVertices; }
const float* LightControlTestMeshSphereModel::GetVertexPositions() const { return kPosition; }
const float* LightControlTestMeshSphereModel::GetVertexNormals() const { return kNormal; }
