// Generated by collada_converter.py
#ifndef _LIGHT_CONTROL_TEST_MESH_SUZANNE_MODEL_H_
#define _LIGHT_CONTROL_TEST_MESH_SUZANNE_MODEL_H_

#include "model_builder.h"

class LightControlTestMeshSuzanneModel : public SolidColorModelBuilder {
 public:
  LightControlTestMeshSuzanneModel() : SolidColorModelBuilder() {}
  LightControlTestMeshSuzanneModel(const vector_t &diffuse, const vector_t &specular)
      : SolidColorModelBuilder(diffuse, specular) {}

  [[nodiscard]] uint32_t GetVertexCount() const override;

 protected:
  [[nodiscard]] const float *GetVertexPositions() const override;
  [[nodiscard]] const float *GetVertexNormals() const override;
};

#endif  // _LIGHT_CONTROL_TEST_MESH_SUZANNE_MODEL_H_