// Generated by collada_converter.py
#ifndef _LIGHT_CONTROL_TEST_MESH_CYLINDER_MODEL_H_
#define _LIGHT_CONTROL_TEST_MESH_CYLINDER_MODEL_H_

#include <cstdint>

#include "model_builder.h"
#include "xbox_math_types.h"

class LightControlTestMeshCylinderModel : public SolidColorModelBuilder {
 public:
  LightControlTestMeshCylinderModel() : SolidColorModelBuilder() {}
  LightControlTestMeshCylinderModel(const vector_t &diffuse, const vector_t &specular)
      : SolidColorModelBuilder(diffuse, specular) {}
  LightControlTestMeshCylinderModel(const vector_t &diffuse, const vector_t &specular, const vector_t &back_diffuse,
                                    const vector_t &back_specular)
      : SolidColorModelBuilder(diffuse, specular, back_diffuse, back_specular) {}

  [[nodiscard]] uint32_t GetVertexCount() const override;

 protected:
  [[nodiscard]] const float *GetVertexPositions() override;
  [[nodiscard]] const float *GetVertexNormals() override;
  void ReleaseData() override {
    if (vertices_) {
      delete[] vertices_;
      vertices_ = nullptr;
    }
    if (normals_) {
      delete[] normals_;
      normals_ = nullptr;
    }
    if (texcoords_) {
      delete[] texcoords_;
      texcoords_ = nullptr;
    }
  }

  float *vertices_{nullptr};
  float *normals_{nullptr};
  float *texcoords_{nullptr};
};

#endif  // _LIGHT_CONTROL_TEST_MESH_CYLINDER_MODEL_H_
