// Generated by collada_converter.py

#include "light_control_test_mesh_cone_model.h"

#include "light_control_test_mesh_cone_mesh.h"

uint32_t LightControlTestMeshConeModel::GetVertexCount() const { return kNumVertices; }
const float* LightControlTestMeshConeModel::GetVertexPositions() const { return kPosition; }
const float* LightControlTestMeshConeModel::GetVertexNormals() const { return kNormal; }
