// Generated by collada_converter.py

#include "light_control_test_mesh_cylinder_model.h"

#include "light_control_test_mesh_cylinder_mesh.h"

uint32_t LightControlTestMeshCylinderModel::GetVertexCount() const { return kNumVertices; }
const float* LightControlTestMeshCylinderModel::GetVertexPositions() const { return kPosition; }
const float* LightControlTestMeshCylinderModel::GetVertexNormals() const { return kNormal; }
